import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { TopNav } from '../components/TopNav';
import { Card, CardContent } from '../components/ui/card';
import { CategoryBadge } from '../components/CategoryBadge';
import { CheckCircle } from 'lucide-react';
import { useAppState } from '../state/AppState';
export default function HistoryPage() {
    const { donations } = useAppState();
    const completedDonations = donations.filter((p) => p.status === 'delivered');
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx(TopNav, {}), _jsxs("div", { className: "max-w-7xl mx-auto px-4 py-8", children: [_jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900 mb-2", children: "Donation History" }), _jsx("p", { className: "text-gray-600", children: "View all completed donations" })] }), _jsx("div", { className: "grid grid-cols-1 gap-4", children: completedDonations.map((post) => (_jsx(Card, { className: "border-green-200", children: _jsx(CardContent, { className: "p-6", children: _jsx("div", { className: "flex items-start justify-between", children: _jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center gap-4 mb-3", children: [_jsx(CheckCircle, { className: "w-6 h-6 text-green-600" }), _jsx("h3", { className: "text-xl font-semibold text-gray-900", children: post.foodName }), _jsx(CategoryBadge, { category: post.category }), _jsx("span", { className: "px-3 py-1 rounded-full text-sm font-medium bg-green-100 text-green-700", children: "Delivered" })] }), _jsxs("div", { className: "grid grid-cols-2 md:grid-cols-5 gap-4 text-sm text-gray-600", children: [_jsxs("div", { children: [_jsx("span", { className: "font-medium", children: "Donor:" }), " ", post.donorName] }), _jsxs("div", { children: [_jsx("span", { className: "font-medium", children: "Quantity:" }), " ", post.quantity] }), _jsxs("div", { children: [_jsx("span", { className: "font-medium", children: "NGO:" }), " ", post.acceptedBy] }), _jsxs("div", { children: [_jsx("span", { className: "font-medium", children: "Distance:" }), " ", post.distance, " km"] }), _jsxs("div", { children: [_jsx("span", { className: "font-medium", children: "Volunteer:" }), " ", post.volunteerId || 'N/A'] })] })] }) }) }) }, post.id))) }), completedDonations.length === 0 && (_jsx(Card, { children: _jsx(CardContent, { className: "p-12 text-center", children: _jsx("p", { className: "text-gray-600", children: "No completed donations yet" }) }) }))] })] }));
}
